# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15efc36f755bc7e5daa666c5a9a40c9a8c0f4f1fcbaa8551bceeca100c34896492f7ed8dcf1b6b4c2980ad9a76b0c524db21e7cb79c9e89ae8b31a477c3a09ba

test:
  secret_key_base: 54435db07f3c1190254a156f32566d9d8e090fd8edf9a77d4c07c8eb2f3ea6c33e73ef18f942e30704e58cc902e9f8116a8ed7c624a620520efc2d2979472c3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
